export const Items = [
    {
        id: 1,
        category: 'Proteins',
        ProductName: 'protein powder',
        productionPrice: 1200,
        rating: 4,
        genre: 'Nigerian',
        description: 'Protein-rich foods',
        image: require('./assets/protein.jpeg'),
    },
    {
        id: 2,
        category: 'Vegetables',
        ProductName: 'Green Pea',
        productionPrice: 2300,
        rating: 4,
        genre: 'Nigerian',
        description: 'for fried rice',
        image: require('./assets/f2.jpeg'),
    },
    {
        id: 3,
        category: 'Fat',
        ProductName: 'butter',
        productionPrice: 3200,
        rating: 4,
        genre: 'Nigerian',
        description: 'Spread on bread',
        image: require('./assets/fat.jpeg'),
    },
    {
        id: 4,
        category: 'Starch',
        ProductName: 'Cassava Flour',
        productionPrice: 450,
        rating: 4,
        genre: 'Nigerian',
        description: 'Soak with fried Chicken',
        image: require('./assets/starch.jpeg'),
    },
    {
        id: 5,
        category: 'Pasteries',
        ProductName: 'Puff Puff',
        productionPrice: 1799,
        rating: 4,
        genre: 'Nigerian',
        description: 'susage meat pie',
        image: require('./assets/pastries.jpeg'),
    },
    {
        id: 6,
        category: 'Fruits',
        ProductName: 'Water Melon',
        productionPrice: 500,
        rating: 4,
        genre: 'Nigerian',
        description: 'water melon juice',
        image: require('./assets/f1.jpeg'),
    },
    {
        id: 7,
        category: 'Proteins',
        ProductName: 'Egg',
        productionPrice: 1800,
        rating: 4,
        genre: 'Nigerian',
        description: 'Up to 20 ass |',
        image: require('./assets/protein.jpeg'),
    },
    {
        id: 8,
        category: 'Vegetables',
        ProductName: 'Carrots',
        productionPrice: 700,
        rating: 4,
        genre: 'Nigerian',
        description: 'Fried Rice Ingredients',
        image: require('./assets/f3.jpeg'),
    },
    {
        id: 9,
        category: 'Fat',
        ProductName: 'Beef',
        productionPrice: 2500,
        rating: 4,
        genre: 'Nigerian',
        description: 'Delicious Beef',
        image: require('./assets/fat.jpeg'),
    },
    {
        id: 10,
        category: 'Starch',
        ProductName: 'Fried Yam',
        productionPrice: 1000,
        rating: 4,
        genre: 'Nigerian',
        description: 'Delicious Fried Yam',
        image: require('./assets/starch.jpeg'),
    },
    {
        id: 11,
        category: 'Pasteries',
        ProductName: 'Pie',
        productionPrice: 1700,
        rating: 4,
        genre: 'Nigerian',
        description: 'Up to 20 horful Bass |',
        image: require('./assets/pastries.jpeg'),
    },
    {
        id: 12,
        category: 'Fruits',
        ProductName: 'Amond Fruit',
        productionPrice: 6000,
        rating: 4,
        genre: 'Nigerian',
        description: 'Up to 20 houwerful Bass |',
        image: require('./assets/f4.jpeg'),
    },

];

export const category = [
    {
        id: 1,
        category: 'Vegetables',
        image: require('./assets/f2.jpeg'),
        catDesc: 'vegetables'
    },
    {
        id: 2,
        category: 'Proteins',
        image: require('./assets/protein.jpeg'),
        catDesc: 'Protein'
    },    {
        id: 3,
        category: 'Fat',
        image: require('./assets/fat.jpeg'),
        catDesc: 'Fat'
    },
    {
        id: 4,
        category: 'Starch',
        image: require('./assets/starch.jpeg'),
        catDesc: 'Starch'
    },    
    {
        id: 5,
        category: 'Pasteries',
        image: require('./assets/pastries.jpeg'),
        catDesc: 'Pasteries'
    },
    {
        id: 6,
        category: 'Fruits',
        image: require('./assets/f1.jpeg'),
        catDesc: 'Fruits'
    },  
]