export const Items = [
    {
        id: 1,
        category: 'Proteins',
        quantity: 1,
        ProductName: 'protein powder',
        productionPrice: 1200,
        rating: 4,
        genre: 'Nigerian Food',
        quantity: 1,
        description: 'Protein-rich foods',
        image: require('../assets/protein.jpeg'),
    },
    {
        id: 2,
        category: 'Vegetables',
        ProductName: 'Green Pea',
        productionPrice: 2300,
        quantity: 1,
        rating: 4,
        genre: 'Nigerian Food',
        quantity: 1,
        description: 'A diet rich in vegetables and fruits can lower blood pressure, reduce the risk of heart disease and stroke, prevent some types of cancer, lower risk of eye and digestive problems, and have a positive effect upon blood sugar, which can help keep appetite in check.',
        image: require('../assets/f2.jpeg'),
    },
    {
        id: 3,
        category: 'Fat',
        ProductName: 'butter',
        quantity: 1,
        productionPrice: 3200,
        rating: 4,
        genre: 'Nigerian',
        description: 'Spread on bread',
        quantity: 1,
        image: require('../assets/fat.jpeg'),
    },
    {
        id: 4,
        category: 'Starch',
        ProductName: 'Cassava Flour',
        quantity: 1,
        productionPrice: 450,
        rating: 4,
        genre: 'Nigerian',
        description: 'Soak with fried Chicken',
        quantity: 1,
        image: require('../assets/starch.jpeg'),
    },
    {
        id: 5,
        category: 'Pasteries',
        ProductName: 'Puff Puff',
        quantity: 1,
        productionPrice: 1799,
        rating: 4,
        genre: 'Nigerian',
        description: 'susage meat pie',
        quantity: 1,
        image: require('../assets/pastries.jpeg'),
    },
    {
        id: 6,
        category: 'Fruits',
        ProductName: 'Water Melon',
        quantity: 1,
        productionPrice: 500,
        rating: 4,
        genre: 'Nigerian',
        description: 'water melon juice',
        quantity: 1,
        image: require('../assets/f1.jpeg'),
    },
    {
        id: 7,
        category: 'Proteins',
        ProductName: 'Egg',
        quantity: 1,
        productionPrice: 1800,
        rating: 4,
        genre: 'Nigerian',
        description: 'Up to 20 ass |',
        quantity: 1,
        image: require('../assets/pro.jpg'),
    },
    {
        id: 8,
        category: 'Vegetables',
        quantity: 1,
        ProductName: 'Carrots',
        productionPrice: 700,
        rating: 4,
        genre: 'Nigerian',
        quantity: 1,
        description: 'A diet rich in vegetables and fruits can lower blood pressure, reduce the risk of heart disease and stroke, prevent some types of cancer, lower risk of eye and digestive problems, and have a positive effect upon blood sugar, which can help keep appetite in check.',
        image: require('../assets/f3.jpeg'),
    },
    {
        id: 9,
        category: 'Fat',
        ProductName: 'Beef',
        quantity: 1,
        productionPrice: 2500,
        rating: 4,
        genre: 'Nigerian',
        description: 'Delicious Beef',
        quantity: 1,
        image: require('../assets/fa.jpg'),
    },
    {
        id: 10,
        category: 'Starch',
        ProductName: 'Fried Yam',
        quantity: 1,
        productionPrice: 1000,
        rating: 4,
        genre: 'Nigerian',
        description: 'Delicious Fried Yam',
        quantity: 1,
        image: require('../assets/starch.jpeg'),
    },
    {
        id: 11,
        category: 'Pasteries',
        quantity: 1,
        ProductName: 'Pie',
        productionPrice: 1700,
        rating: 4,
        genre: 'Nigerian',
        description: 'Up to 20 horful Bass |',
        quantity: 1,
        image: require('../assets/pastries.jpeg'),
    },
    {
        id: 12,
        category: 'Fruits',
        quantity: 1,
        ProductName: 'Amond Fruit',
        productionPrice: 6000,
        rating: 4,
        genre: 'Nigerian',
        description: 'Up to 20 houwerful Bass |',
        quantity: 1,
        image: require('../assets/f4.jpeg'),
    },

];

export const category = [
    {
        id: 1,
        category: 'Vegetables',
        image: require('../assets/f2.jpeg'),
        catDesc: 'Delicious Vegetables'
    },
    {
        id: 2,
        category: 'Proteins',
        image: require('../assets/protein.jpeg'),
        catDesc: 'Protein Gain'
    },    {
        id: 3,
        category: 'Fat',
        image: require('../assets/fat.jpeg'),
        catDesc: 'Fat'
    },
    {
        id: 4,
        category: 'Starch',
        image: require('../assets/starch.jpeg'),
        catDesc: 'Starch'
    },    
    {
        id: 5,
        category: 'Pasteries',
        image: require('../assets/pastries.jpeg'),
        catDesc: 'Yummy Pasteries'
    },
    {
        id: 6,
        category: 'Fruits',
        image: require('../assets/f1.jpeg'),
        catDesc: 'Look Fresh with Fruits'
    },  
]

export const board = [
    {
        id: 1,
        image: require('../assets/5ea4588bb033640004a14ad2.png'),
        title: "Live-Check",
        description: "Allow users to check the availability of food"
    },
    {
        id: 2,
        image: require('../assets/5bbf074adbc29e02dd827848.png'),
        title: "Online Menu",
        description: "Allow users to check the real-time menus in our restaurant"
    },
    {
        id: 3,
        image: require('../assets/59bedb387a216d0b052f128d.png'),
        title: "Easy Delivery",
        description: "Order the food you want and it will be delivered to you"
    },
]